services:
  api:
    build: 
      context: .
      args:
        - USER_ID=1000
        - GROUP_ID=1000
    ports:
      - "8000:8000"
    volumes:
      - .:/app:z
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:z
    ports:
      - "5432:5432"

volumes:
  pgdata:
